#!/bin/bash

cd ./node_modules/kaku-thanks/Obstructing-Trio && python setup.py install && rm -R build
cd ./node_modules/kaku-thanks/Fasternix-Stratalorn && python setup.py install && rm -R build
cd ./
